"""Add alert_workflow_state table

Revision ID: d32eb29d44c1
Revises: b3c4d5e6f7g8
Create Date: 2026-05-17 02:28:04.625245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32eb29d44c1'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7g8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_workflow_state',
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('clear_reason', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_alert_workflow_state_entity_id'), 'alert_workflow_state', ['entity_id'], unique=False)
    op.create_index(op.f('ix_resolved_events_simulation_partition'), 'resolved_events', ['simulation_partition'], unique=False)
    op.create_index(op.f('ix_resolved_events_timestamp'), 'resolved_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resolved_events_timestamp'), table_name='resolved_events')
    op.drop_index(op.f('ix_resolved_events_simulation_partition'), table_name='resolved_events')
    op.drop_index(op.f('ix_alert_workflow_state_entity_id'), table_name='alert_workflow_state')
    op.drop_table('alert_workflow_state')
    # ### end Alembic commands ###
